version: '3.8'

services:
  # 1. MongoDB Database
  mongo:
    image: mongo:latest
    container_name: auth-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: auth-rabbitmq
    ports:
      - "5672:5672"   # App Port
      - "15672:15672" # Dashboard Port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo-data: