version: '3.8'

services:
  # 1. MongoDB Database
  mongo:
    image: mongo:latest
    container_name: auth-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: auth-rabbitmq
    ports:
      - "5672:5672"   # App Port
      - "15672:15672" # Dashboard Port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # 3. Redis (The SignalR Backplane)
  redis:
    image: redis:alpine
    container_name: auth-redis
    ports:
      - "6379:6379"

  # 4. .NET API (The Backend)
  api:
    build: .
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      # Database Connections
      - MongoDB__ConnectionURI=mongodb://mongo:27017
      - MassTransit__Host=rabbitmq
      
      
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    depends_on:
      - mongo
      - rabbitmq
      - redis

volumes:
  mongo-data: